### ISSUE TITLE
Final project

### ISSUE THREAD

**Issue by marina-cyber** [PojilayaProgrmmaDOOMER/time_series_hw#10]
Возьмите 3 любые другие линии временных рядов из набора.

min. max, mea - статистически не различимы.

**Comment by PojilayaProgrmmaDOOMER** [comment]
Здравствуйте,  поменял линии. Теперь есть mea, MeanTemp, Precip. MEA - это средняя температура в фаренгейтах а MeanTemp - средняя в цельсиях. И интересно, что в фаренгейтах прогнозы лучше(именно поэтому взял эти два, для эксперемента). В выводу преположил почему так получилось! Смотреть надо файл - final_project_Fixed.ipynb.

**Comment by marina-cyber** [comment]
Проект зачтен
